
SELECT * FROM TB_USER;

COMMIT;CREATE TABLE TB_USER(
	USER_NO     NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
	USER_ID     VARCHAR2(30) NOT NULL,
	USER_PW     VARCHAR2(30) NOT NULL,
	USER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_USER.USER_NO     IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID     IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME   IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';


-- USER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT * FROM TB_USER;

COMMIT;


-- 모든 USER 조회
SELECT
	USER_NO,
	USER_ID,
	USER_PW,
	USER_NAME,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM "월" DD"일"')ENROLL_DATE
FROM TB_USER
ORDER BY USER_NO ASC;

-- 검색어가 이름에 포함된 User 조회
SELECT
	USER_NO,
	USER_ID,
	USER_PW,
	USER_NAME,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM "월" DD"일"')ENROLL_DATE
FROM TB_USER
WHERE USER_NAME LIKE '%' || '홍' || '%'
ORDER BY USER_NO ASC;

-- USER_NO를 입력받아 일치하는 User 삭제(DELETE)
DELETE
FROM TB_USER
WHERE
	USER_NO = 2;

SELECT * FROM TB_USER;

COMMIT;

ROLLBACK;
-- 일치하는 USER_NO가 있을경우 : 1행 삭제
-- 일치하는 USER_NO가 없을경우 : 0행 삭제
	
-- ID, PW가 일치하는 회원의 USER_NO(PK) 조회
SELECT USER_NO
FROM TB_USER
WHERE USER_ID = '로땡땡땡'
AND USER_PW = 'roddang12';

-- USER_NO(PK)가 일치하는 회원의 이름을 수정
UPDATE TB_USER
SET USER_NAME = '로스트템플'
WHERE USER_NO = 6;

SELECT * FROM TB_USER;
	
-- 중복되는 아이디가 있는지 조회
SELECT COUNT(*)
FROM TB_USER
WHERE USER_ID = 'user01';

-- 업데이트
UPDATE TB_USER
SET USER_NAME = '개마고원', USER_PW = 'user05';

INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user28', '*콩순이순이*', '콩순이', DEFAULT );

SELECT USER_NAME
FROM TB_USER
WHERE USER_PW LIKE '%*%';
COMMIT;











