

SELECT 
	AREA_NAME 지역명, 
	MEMBER_ID 아이디, 
	MEMBER_NAME 이름, 
	GRADE_NAME 등급명
FROM 
	TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA USING(AREA_CODE)
WHERE AREA_CODE = (SELECT AREA_CODE FROM TB_MEMBER
WHERE MEMBER_NAME = '김영희')
ORDER BY 이름 ASC;



SELECT * FROM TB_MEMBER
WHERE AREA_CODE = (SELECT AREA_CODE FROM TB_MEMBER
WHERE MEMBER_NAME = '김영희')