
-- - MEMBERS 테이블 
-- 1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정.
-- 2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정.
-- 3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정.


-- MEMBERS 테이블 생성

DROP TABLE MEMBERS;

CREATE TABLE MEMBERS(

MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,

MEMBER_PWD VARCHAR2(20) NOT NULL,

MEMBER_NAME VARCHAR2(30),

MEMBER_AGE NUMBER,

MEMBER_EMAIL VARCHAR2(50)

);

INSERT INTO MEMBERS
VALUES('user01', 'pass01', '홍길동', '25', 'hong123@kh.or.kr');

INSERT INTO MEMBERS
VALUES('user02', 'pass01', '홍길동', '25', 'hong123@kh.or.kr');

SELECT * FROM MEMBERS;


ROLLBACK;

-- BOARDS 테이블 
-- 1) BOARD_NO 컬럼에 PRIMARY KEY 제약조건 설정.
-- 2) BOARD_WRITER 컬럼에 MEMERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정.
-- 3) BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정


-- BOARDS 테이블 생성

CREATE TABLE BOARDS(

BOARD_NO NUMBER PRIMARY KEY,

BOARD_TITLE VARCHAR2(100),

BOARD_CONTENT VARCHAR2(4000),

BOARD_WRITER VARCHAR2(20),
 
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE

,  CONSTRAINT BOARD_WRITER_FK
	 FOREIGN KEY(BOARD_WRITER)
	 REFERENCES MEMBERS(MEMBER_ID)
);






